#!/usr/bin/env bash

# シンボリックリンクで呼び出した場合、実体を辿る
if [ -L "$0" ]
then
  dir=$(dirname "$(dirname "$0")/$(readlink "$0")")
else
  dir=$(dirname "$0")
fi

# nexeのバイナリがある場合はそちらを優先する
if [ -f "$dir"/fl9.bin ]
then
  NODE_PATH="$dir" exec "$dir"/fl9.bin "$@"
else
  NODE_PATH="$dir" exec node "$dir"/fl9.js "$@"
fi
