#!/usr/bin/env bash

# シンボリックリンクで呼び出した場合、実体を辿る
if [ -L "$0" ]
then
  dir=$(cd "$(dirname "$0")"; cd "$(dirname "$(readlink "$0")")"; pwd)
else
  dir=$(cd "$(dirname "$0")"; pwd)
fi

# nexeのバイナリがある場合はそちらを優先する
if [ -f "$dir"/fl9.bin ]
then
  NODE_PATH=$dir exec "$dir"/fl9.bin "$@"
else
  NODE_PATH=$dir exec node "$dir"/fl9.js "$@"
fi
