#!/usr/bin/env bash

# シンボリックリンクで呼び出した場合、実体を辿る
if [ -L "$0" ]
then
  dir=$(cd "$(dirname "$0")"; cd "$(dirname "$(readlink "$0")")"; pwd)
else
  dir=$(cd "$(dirname "$0")"; pwd)
fi

# 実体の外側に出て、その場所から実体をアップデート
cd "$dir"
cd ../../..
bash "$dir"/download.sh
