name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: "src/web/*.md"
          TOC_TITLE: ""
          COMMIT_NAME: "toc-generator"
          COMMIT_EMAIL: ""

      - name: Build
        run: bash gradlew build

      - name: Compile
        run: |
          cd build/web/release
          bash make.sh

      - name: Test
        run: bash test.js

      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: doc
          publish_dir: ./build/web
          enable_jekyll: true
