name: Toc

on:
  push:
    branches: [ doc ]
  pull_request:
    branches: [ doc ]
  workflow_dispatch:

jobs:
  generateTOC:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_PATHS: "*.md"
